GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTExNGZlMy1mYzA4LTRmMTEtYjc1NS0yY2VkZjViOWIwODEiLCJnaXZlbl9uYW1lIjoiVmljdG9yIiwiZmFtaWx5X25hbWUiOiJBemV2ZWRvIiwianRpIjoiNzFlNjNjYzAtYjJhMi00YTM2LTlhYzgtNWM2YjQyYTMyNWIwIiwiZXhwIjoxNzA5MTQ0MjY4LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.eyt_GQOtiYkjyetHGkWv9AvFouvdcudBUXi7E4XaYKs