@hostId=dasda
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYTNiN2QxNy02MDRkLTRjNTMtYjc1NC0zNTdkYmMxZTQwNTIiLCJnaXZlbl9uYW1lIjoiVmljdG9yIiwiZmFtaWx5X25hbWUiOiJBemV2ZWRvIiwianRpIjoiNjM5OGQ1YmQtNzdlZi00ZWU1LWI3NzQtZmZmMzhhZTliZWU0IiwiZXhwIjoxNzA5NzAzNTMwLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.c7OKcI1B5aWcypgS0ya8OAMvoVmCRHmZCogmulyxJrU

POST {{host}}/hosts/{{$guid}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Yummy Menu",
  "description": "A menu with yummy food",
  "sections": [
    {
      "name": "Appetizers",
      "description": "Starters",
      "items": [
        {
          "name": "Fried Pickles",
          "description": "Deep fried pickles"
        }
      ]
    }
  ]
}