GET {{host}}/dinners
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYmMyZjRhNy0xMjdlLTRlODctYmNiMS1iYjdjZmY3YjNiNzkiLCJnaXZlbl9uYW1lIjoiVmljdG9yIiwiZmFtaWx5X25hbWUiOiJBemV2ZWRvIiwianRpIjoiY2JjOWM3ZGEtNzA5My00OTI5LWFiNjgtNzUyZGZhMTIyNmI4IiwiZXhwIjoxNzA5MTM5NjQ4LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.cBt2jdGuFBN4v1BXgSsihRh0jLR9vu1olOGQ5prkel4