GET {{host}}/dinners
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNWM2MTc4ZS0zMGE1LTQ2YWItODk4Zi1jNzlkYzlhY2FkNGUiLCJnaXZlbl9uYW1lIjoiVmljdG9yIiwiZmFtaWx5X25hbWUiOiJBemV2ZWRvIiwianRpIjoiYWQ3MWFhZGMtZGRjYi00Y2FiLWI3ZmMtNDU3YThmMjFmNzhhIiwiZXhwIjoxNzA5MzE1MjM2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.Zg-91__bipArJigIlngtlc6rtK_mpY8Vv8Rmd3iS7tg